07/02 02:23:06 PM: fastText library not found!
DONE
07/02 02:23:07 PM: Fatal error in main():
Traceback (most recent call last):
  File "/usr/share/anaconda3/lib/python3.6/site-packages/pyhocon/config_parser.py", line 286, in _resolve_variable
    return True, config.get(variable)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/pyhocon/config_tree.py", line 190, in get
    return self._get(ConfigTree.parse_key(key), 0, default)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/pyhocon/config_tree.py", line 139, in _get
    raise ConfigMissingException(u"No configuration setting found for key {key}".format(key='.'.join(key_path[:key_index + 1])))
pyhocon.exceptions.ConfigMissingException: No configuration setting found for key NFS_PROJECT_PREFIX

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/main.py", line 200, in <module>
    main(sys.argv[1:])
  File "src/main.py", line 52, in main
    args = config.params_from_file(cl_args.config_file, cl_args.overrides)
  File "/home/raghu1991_p_gmail_com/jiant_v2/src/config.py", line 94, in params_from_file
    config = pyhocon.ConfigFactory.parse_string(config_string, basedir=basedir)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/pyhocon/config_parser.py", line 90, in parse_string
    return ConfigParser().parse(content, basedir, resolve)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/pyhocon/config_parser.py", line 274, in parse
    ConfigParser.resolve_substitutions(config)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/pyhocon/config_parser.py", line 420, in resolve_substitutions
    is_optional_resolved, resolved_value = ConfigParser._resolve_variable(config, substitution)
  File "/usr/share/anaconda3/lib/python3.6/site-packages/pyhocon/config_parser.py", line 299, in _resolve_variable
    col=col(substitution.loc, substitution.instring)))
pyhocon.exceptions.ConfigSubstitutionException: Cannot resolve variable ${NFS_PROJECT_PREFIX} (line: 19, col: 15)
